export enum TankTypes {
  PEER_MOVE,
  TILE_PUNCH = 3,
  PEER_WORLD,
  TILE_UPDATE,
  PEER_ENTER_DOOR = 7,
  TILE_DAMAGE,
  PEER_INVENTORY,
  PEER_COLLECT = 11,
  TILE_TREE,
  PEER_DROP = 14,
  TILE_APPLY_LOCK,
  PEER_ITEMS_DAT,
  PEER_ICON = 18,
  PEER_PING_RESPONSE = 21,
  PEER_PING_REQUEST
}
